### ISSUE TITLE
Decide on versioning for non–Perl packages

### ISSUE THREAD

**Issue by ksurent** [xsawyerx/pakket#39]
Currently we depend on Perl's `version` to parse and sort version numbers. This works well for Perl packages but not so much for everything else. We need either an abstraction over different schemes or to re–version everything in accordance with Perl's versioning scheme. Preferably the former.

**Comment by ksurent** [comment]
I suggest we introduce a new package–level config file, say `versioning.toml`, to define which versioning scheme to should be used for this package. The value in that config should also map to a Perl module that will define version comparison methods.

**Comment by xsawyerx** [comment]
We should definitely have a package-level comparable, allowing packages to override. Whether it's in a config or not does not matter, since the general versioning won't be changed. That is, the way you compare Perl modules will *always* be the same. Same for Python, Ruby, etc. The overrides will go in the config-file instead.

**Comment by ksurent** [comment]
Why would we want to override versioning of a package? How do we compare versions of the same package in different formats?
Also, not all categories will have a well defined versioning scheme. Think about native packages.

**Comment by xsawyerx** [comment]
Versioning is now per-category and per-package.
There are two versioning schemes at the moment: Default and SemVer, with ability to write more in the future.

I consider this topic closed. Thanks.
