### ISSUE TITLE
Implement our own Pakket versioning scheme

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/pakket#75]
We can implement our own versioning scheme in order to make all versions adhere to one consistent scheme.
- [x] `1.2.3` - Minimum version. (this and above.)
- [x] `== 1.2.3` - Exact version.
- [x] `!= 1.2.3` - Not version.
- [x] `>` - Greater than.
- [x] `<` - Less than.
- [x] `<=`, `>=` - Greater and equal, less and equal.
- [x] A list of the above, implying "AND" condition between them.

**Comment by gonzus** [comment]
The logical operations you might want to do with a version string are, I think, quite obvious. And writing a mini-parser that can interpret a sequence of these operations should be easy enough.

I believe the hard(er) thing here will be: how do you actually define the (total) order for a version value? In other words, how do you compare 1.0, 1.2.3, 1.3-alpha, 1.2-0.1-i-love-beer, orange-ocelot-2.5, unstable-0.5, etc? Some method must be introduced into this madness, but I'm not sure how to go about it.

If worse comes to worst, we could support some useful cases that might cover 80% of the universe (semver, straight numbers, lexicographical comparisons) and, for the pathological cases, we could have a file listing all known versions for that package in ascending order, so that the order in the file defines the (total) order for the versions for this particular package.

**Comment by xsawyerx** [comment]
Done and merged. :)
